### PR TITLE
update README.md to test BehaviorBot

### PR DESCRIPTION
**Pull request by eirini-zormpa**
Hi Sophia, just checking if BehaviorBot responds 🤖

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Oh this is cute! And yay for it triggering correctly.

**Review by BrainonSilicon — APPROVED** [review]
Looks great to me! 

Merge away @eirini-zormpa 🚀

**Comment by eirini-zormpa** [comment]
hmm I don't think I can have write access (i.e. can't merge)?

**Review by BrainonSilicon — APPROVED** [review]
Love the emoji update! Checking some repo configurations to figure out why you can't merge.

**Pull request merged**
